### ISSUE TITLE
how the tool works on a quary that's not overlapping with any bins

### ISSUE THREAD

**Issue by shiyi-pan** [changlabtw/hicmaptools#3]
Hi, I think this is a wonderful tool to deal with HiC data just what I'm looking for . 

But I have one question about it. In the fly_30k.cbins file , bins is a sliding window with 0 as the starting point and 30kb as the interval. The query file such as pair.bed, the locations are irregular, not overlapping with any bins in  fly_30k.cbins file, So how the tool assigns an contact in bin such as "0-30kb" into a location "29000-31111kb"?

Hope to reply me soon. Thank you very much.

**Comment by jmchangTW** [comment]
First, the position of the query file is assigned to the overlapped bin.
i.e., pair.bed
3R	952484	953085	3R	1094107	1094708
is assigned as bin 2306 & 2311.
3R	952484	953085 => overlap, 2306	3R	930000	960000	132 (in fly_30k.cbins)
3R	1094107	1094708=> overlap, 2311	3R	1080000	1110000	150

Then, two bins, 2306 and 2311, are used as index to find the corresponding contact frequency of hic contact matrix.

Don't hesitate to reply if anything is not clear.
btw, sorry for the late reply since I don't notice there are issues posted in the GitHub.

**Comment by shiyi-pan** [comment]
Hi, if the bin 2306 & 2311 has 300 contacts, then how to calculate the contacts between "3R 952484 953085" and "3R 1094107 1094708" ? Is it distributed proportionally to length? 
sorry for reply late, I submit two questions and I  focus on another one.

**Comment by jmchangTW** [comment]
Once the query is assigned to bins, then HiCmapTools calculates the contact frequency between two bins (2306 vs 2311). It means the calculation is based on the whole bin instead of proportionally length. We might add a proportion option in the next version for a more precise calculation.

**Comment by shiyi-pan** [comment]
Thank you for your reply. In my practise, TADbits has good performance at mapping HiC reads to genomes, but the hicmaptools could compatible it. could you make hicmaptools accept the output file of tadbits if it's convenient for you.
Thank you again.

**Comment by jmchangTW** [comment]
A good suggestion. We will study how to parse TADbits output into our data structure and keep you posted when it is done.
